version: "3.1"

services:
  postgresdb:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=asp_admin
      - POSTGRES_PASSWORD=asp_admin
      - POSTGRES_DB=aspSolutions

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "asp_admin@admin.es"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - postgresdb

  api:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "8080:3100"
    depends_on:
      - postgresdb
    environment:
      DATABASE_URL: postgresql://postgresdb:5432/aspSolutions
      DATABASE_USER: asp_admin
      DATABASE_PASSWORD: asp_admin
